services:
  homeassistant:
    build: .
    image: nl-rain-forecast-dev
    container_name: nl-rain-forecast-dev
    ports:
      - "8123:8123"
    volumes:
      # For a new seed, remove this comment.
      # - ./config:/config
      - ./custom_components/nl_rain_forecast:/config/custom_components/nl_rain_forecast:ro
    environment:
      - TZ=Europe/Amsterdam
    stop_grace_period: 30s
